# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name=b'date and time of gig')),
                ('location_name', models.CharField(max_length=200)),
                ('location_link', models.URLField()),
                ('fb_event', models.URLField()),
            ],
        ),
    ]
